minio:
  podSecurityContext:
    enabled: false
  containerSecurityContext:
    enabled: false
  fullnameOverride: uff-minio
  replicas: 1
  persistence:
    size: 50Gi
    storageClass: "safe"
    accessModes:
      - ReadWriteMany
  auth:
    existingSecret: "loki-backend-secret"
  resources:
    requests:
      memory: 2Gi #default 4Gi bei 500Gi persistent storage. Sollte mit weniger auch auskommen.
    limits:
      memory: 4Gi
  makeBucketJob:
    securityContext:
      enabled: true
      runAsUser: 0
  serviceAccount:
    create: true
    automountServiceAccountToken: true
  provisioning:
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
    enabled: true
    buckets:
      - name: loki
        purge: false
        policy: none
